In [10]:
import matplotlib.image as mpimg
img = mpimg.imread('dog.jpeg')

In [11]:
import numpy as np

red, green, blue = img[:, :, 0], img[:, :, 1], img[:, :, 2]

In [12]:
print(red)
print(green)
print(blue)

[[118  89  82 ... 151 151 151]
 [119  89  83 ... 151 151 151]
 [119  90  83 ... 151 150 150]
 ...
 [145 126 119 ... 116 112 110]
 [138 119 112 ... 116 112 110]
 [136 117 109 ... 117 113 111]]
[[134 105  98 ... 163 163 163]
 [135 105  99 ... 163 163 163]
 [135 106  99 ... 164 163 163]
 ...
 [155 136 131 ... 152 149 147]
 [148 129 124 ... 151 149 147]
 [146 127 121 ... 152 149 147]]
[[ 71  42  35 ... 149 149 149]
 [ 72  42  36 ... 149 149 149]
 [ 72  43  36 ... 147 146 146]
 ...
 [ 94  75  65 ...  82  79  77]
 [ 87  68  58 ...  85  80  78]
 [ 85  66  55 ...  88  85  83]]


In [13]:
#Lightness
max_rgb = np.max(np.array([red, green, blue]), axis=0)
min_rgb = np.min(np.array([red, green, blue]), axis=0)

# Print the results
print("Maximum RGB values:", max_rgb)
print("Minimum RGB values:", min_rgb)

ligtness_img = (max_rgb + min_rgb) / 2
mpimg.imsave('dog_lightness.png', ligtness_img)
ligtness_img[0, 0]


Maximum RGB values: [[134 105  98 ... 163 163 163]
 [135 105  99 ... 163 163 163]
 [135 106  99 ... 164 163 163]
 ...
 [155 136 131 ... 152 149 147]
 [148 129 124 ... 151 149 147]
 [146 127 121 ... 152 149 147]]
Minimum RGB values: [[ 71  42  35 ... 149 149 149]
 [ 72  42  36 ... 149 149 149]
 [ 72  43  36 ... 147 146 146]
 ...
 [ 94  75  65 ...  82  79  77]
 [ 87  68  58 ...  85  80  78]
 [ 85  66  55 ...  88  85  83]]


102.5

In [14]:
#Average
avg_rgb = np.mean(np.array([red, green, blue]), axis=0)
mpimg.imsave('dog_avg.png', avg_rgb)
avg_rgb[0, 0]



107.66666666666667

In [15]:
#Luminosity
luminosity_img = 0.2126 * red + 0.7152 * green + 0.0722 * blue
mpimg.imsave('dog_luminosity.png', luminosity_img)
luminosity_img[0, 0]

126.04979999999999